import './globals.css';
import { Box, Center, Flex, Heading, VStack } from '@chakra-ui/react';
import { GoogleAnalytics } from '@next/third-parties/google';
import { Inter } from 'next/font/google';
import Link from 'next/link';

import { Provider } from './Providers';
import ClickableTextLink from './ui/ClickableTextLink';
import { ToggleColorModeButton } from './ui/ToggleColorModeButton';

import type { Metadata } from 'next';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const GA_ID = process.env.NEXT_PUBLIC_GA_ID;

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <html lang="en">
    <body className={inter.className}>
      <Provider>
        <Flex as="header" borderBottom="1px solid" borderColor="border.deep" height="60px">
          <Box p="4" width="860px" margin="0 auto">
            <Link href="/">
              <Heading as="h1" size="md" _hover={{ opacity: 0.6, transition: '0.5s' }}>
                ゆるめの TECH BLOG
              </Heading>
            </Link>
          </Box>
        </Flex>
        <main>
          <Box maxWidth="1024px" margin="0 auto" p={4} minHeight="600px">
            <Flex justifyContent="right" mt={2}>
              <Center>
                <ToggleColorModeButton />
              </Center>
            </Flex>
            {children}
          </Box>
        </main>
        <VStack as="footer" py={4} px={16} mt={12} borderTop="1px solid" borderColor="border.deep">
          <Flex gap={4}>
            <ClickableTextLink href="./disclaimer">免責事項</ClickableTextLink>
            <ClickableTextLink href="./privacy">プライバシーポリシー</ClickableTextLink>
          </Flex>
          <Box>©︎ {new Date().getFullYear()}</Box>
        </VStack>
      </Provider>
    </body>
    <GoogleAnalytics gaId={GA_ID} />
  </html>
);

export default RootLayout;
